### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [xx10t4/iota1k#1]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

electron-builder has native support for AppImage. Please make sure you are using the latest version.
If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by xx10t4** [comment]
I have uploaded a version 0.0.1 AppImage. Please let me know if you experience any issues with it.

https://github.com/xx10t4/iota1k/releases

**Comment by probonopd** [comment]
Thanks, added to https://github.com/AppImage/appimage.github.io/commit/f36e6a1e66256d70329eade4376ccc3e0805baa9

**Comment by xx10t4** [comment]
Cool, thanks! I'll work on getting a better screengrab for it at some point soon.
