### ISSUE TITLE
Cannot set property errorMessage of undefined

### ISSUE THREAD

**Issue by yillkid** [xx10t4/iota1k#15]
I get a error message when I try to create a new account : 

`2/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:1038 checksum KUX
2/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:462 in handler error:  no results in findTransactions callback for tag IOTALKMESSAGE99999999999999
21/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:462 in handler error:  no results in findTransactions callback for tag IOTALKMESSAGE99999999999999
/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:82 ccurlPath: /home/yillkid/workspace/IOTA/iota1k/lib/ccurl/lin64
11/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:462 in handler error:  no results in findTransactions callback for tag IOTALKMESSAGE99999999999999
/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:432 addAccountResultsHandler results.account: {"privateKey":"2,3,0,6,16,86,182,139,119,223,191,133,10,180,49,180,196,9,194,127,160,209,18,66,221,249,171,62,179,148,216,149,238,174,84,227,122,100,113,86,139,46,132,148,35,138,251,67,42,134,204,190,172,24,124,106,20,39,234,35,255,12,13,147,251,142,67,66,222,155,212,199,230,87,138,216,231,220,152,83,181,210,135,202,232,201,173,196,104,200,102,61,142,125,173,192,96,210,119,162,237,123,75,23,201,227,199,225,153,32,136,112,162,57,13,128,77,120,175,166,45,171,146,174,67,134,182,214,32,9,170,149,220,92,47,98,48,12,144,103,243,26,150,137,230,120,224,60,153,146,103,98,105,19,143,246,174,247,168,20,123,74,224,149,13,207,134,77,111,103,21,72,122,61,119,10,134,27,5,219,13,141,48,165,158,82,138,1,14,77,41,51,155,192,248,116,255,75,160,117,181,162,131,185,138,110,145,99,176,172,184,97,201,153,185,116,143,71,187,136,38,194,132,115,250,188,75,34,149,102,74,103,176,220,96,72,91,57,177,67,70,139,95,43,172,95,121,15,241,130,145,176,126,67,143,40,77,231,41,253,187,131,125,190,249,169,18,247,23,129,115,118,142,211,17,45,74,137,135,121,123,138,132,222,233,211,131,16,79,139,251,77,143,140,143,188,178,244,85,213,129,146,240,14,46,15,121,10,66,237,153,52,211,243,57,157,138,137,174,41,85,93,97,3,121,61,100,46,235,249,238,153,146,248,99,97,151,83,51,150,52,193,135,215,242,63,178,93,74,103,152,254,51,249,93,84,104,62,171,192,45,191,33,193,45,113,171,81,237,193,54,153,162,138,208,37,113,179,148,167,58,128,128,174,105,96,68,10,164,113,14,183,125,215,35,162,111,83,161,143,22,16,128,196,213,68,51,119,171,89,123,254,190,181,185,5,21,16,244,71,11,221,19,149,246,143,217,22,200,213,6,25,249,61,230,197,171,212,8,131,94,77,32,110,172,255,28,235,154,70,130,37,207,160,153,245,128,160,70,77,141,145,94,141,21,25,1,223,118,0,58,117,239,145,10,26,19,16,242,10,147,52,132,132,33,83,76,105,146,20,103,189,250,30,184,165,98,46,197,144,174,255,208,23,172,83,78,217,120,10,25,54,21,91,134,210,107,128,190,152,200,10,236,148,50,158,180,80,125,136,244,243,252,201,16,97,35,79,127,136,105,137,190,51,57,194,174,166,156,85,119,78,248,91,80,154,43,197,197,221,22,145,162,79,120,43,23,118,109,120,208,243,244,228,20,236,45,171,218,177,163,240,158,224,182,195,218,7,55,55,47,243,129,32,206,1,92,188,202,41,7,251,43,243,239,17,253,157,68,54,90,142,182,82,101,207,239,201,137,168,0,46,80,253,106,3,141,50,4,146,117,135,127,187,196,174,224,78,137,190,250,1,215,79,59,165,134,166,104,90,60,178,239,177,139,209,98,15,189,92,134,200,252,87,204,178,122,239,24,135,132,211,172,167,149,149,11,213,82,209,64,114,136,167,174,252,38,73,41,43,227,246,32,1,133,167,103,32,126,83,51,195,193,220,248,90,246,159,161,107,17,224,103,242,142,7,97,9,130,230,13,97,139,0,177,72,255,23,6,62,158,65,9,101,38,191,4,16,231,132,45,38,110,217,167,208,132,235,179,212,233,210,98,77,71,35,6,5,111,44,193,92,132,162,57,27,81,74,140,15,60,204,224,229,127,71,22,98,47,92,197,29,201,79,59,90,196,142,34,102,221,4,219,42,133,102,181,74,67,0,168,84,48,47,102,44,90,10,121,234,216,170,204,8,153,53,195,249,252,220,121,176,129,56,119,34,133,176,199,7,114,180,102,20,79,59,246,76,138,3,114,135,70,38,46,190,77,39,234,62,218,109,10,233,42,244,233,153,161,94,17,103,186,59,49,250,99,18,36,206,212,228,245,255,6,89,166,168,164,249,219,79,68,208,202,24,42,118,109,48,81,114,90,250,206,38,25,28,205,75,140,8,251,39,87,212,25,186,212,144,48,89,45,177,169,174,17,175,65,44,7,17,247,48,228,219,17,161,253,218,244,185,255,236,7,229,42,40,229,141,225,254,101,208,73,158,170,234,56,203,246,202,32,52,21,125,110,207,120,21,16,216,143,117,118,108,191,197,123,111,154,217,247,195,238,133,128,211,180,142,230,123,221,251,239,27,147,36,13,81,213,8,114,3,149,111,247,208,178,130,79,24,10,95,37,155,95,236,150,212,101,87,166,252,108,185,102,226,251,115,188,34,144,98,129,234,144,75,23,101,44,57,17,235,233,49,53,31,163,91,41,110,112,96,184,68,75,92,108,184,130,201,97,3,25,244,31,34,31,39,178,18,128,214,116,72,86,62,21,107,22,172,91,130,32,196,117,30,73,58,21,111,172,7,147,249,204,19,103,150,216,31,168,65,153,117,36,129,76,149,246,22,127,142,136,32,137,150,232,40,162,196,99,82,21,88,205,71,213,240","publicKey":"1,3,0,6,16,86,182,139,119,223,191,133,10,180,49,180,196,9,194,127,160,209,18,66,221,249,171,62,179,148,216,149,238,174,84,227,122,100,113,86,139,46,132,148,35,138,251,67,42,134,204,190,172,24,124,106,20,39,234,35,255,12,13,147,251,142,67,66,222,155,212,199,230,87,138,216,231,220,152,83,181,210,135,202,232,201,173,196,104,200,102,61,142,125,173,192,96,210,119,162,237,123,75,23,201,227,199,225,153,32,136,112,162,57,13,128,77,120,175,166,45,171,146,174,67,134,182,214,32,9,170,149,220,92,47,98,48,12,144,103,243,26,150,137,230,120,224,60,153,146,103,98,105,19,143,246,174,247,168,20,123,74,224,149,13,207,134,77,111,103,21,72,122,61,119,10,134,27,5,219,13,141,48,165,158,82,138,1,14,77,41,51,155,192,248,116,255,75,160,117,181,162,131,185,138,110,145,99,176,172,184,97,201,153,185,116,143,71,187,136,38,194,132,115,250,188,75,34,149,102,74,103,176,220,96,72,91,57,177,67,70,139,95,43,172,95,121,15,241,130,145,176,126,67,143,40,77,231,41,253,187,131,125,190,249,169,18,247,23,129,115,118,142,211,17,45,74,137,135,121,123,138,132,222,233,211,131,16,79,139,251,77,143,140,143,188,178,244,85,213,129,146,240,14,46,15,121,10,66,237,153,52,211,243,57,157,138,137,174,41,85,93,97,3,121,61,100,46,235,249,238,153,146,248,99,97,151,83,51,150,52,193,135,215,242,63,178,93,74,103,152,254,51,249,93,84,104,62,171,192,45,191,33,193,45,113,171,81,237,193,54,153,162,138,208,37,113,179,148,167,58,128,128,174,105,96,68,10,164,113,14,183,125,215,35,162,111,83,161,143,22,16,128,196,213,68,51,119,171,89,123,254,190,181,185,5,21,16,244,71,11,221,19,149,246,143,217,22,200,213,6,25,249,61,230,197,171,212,8,131,94,77,32,110,172,255,28,235,154,70,130,37,207,160,153,245,128,160,70,77,141,145,94,141,21,25,1,223,118,0,58,117,239,145,10,26,19,16,242,10,147,52,132,132,33,83,76,105,146,20,103,189,250,30,184,165,98,46,197,144,174,255,208,23,172,83,78,217,120,10,25,54,21,91,134,210,107,128,190,152,200,10,236,148,50,158,180,80,125,136,244,243,252,201,16,97,35,79,127,136,105,137,190,51,57,194,174,166,156,85,119,78,248,91,80,154,43,197,197,221,22,145,162,79,120,43,23,118,109,120,208,243,244,228,20,236,45,171,218,177,163,240,158,224,182,195,218,7,55,55,47,243,129,32,206,1,92,188,202,41,7,251,43,243,239,17,253,157,68,54,90,142,182,82,101,207,239,201,137,168,0,46,80,253,106,3,141,50,4,146,117,135,127,187,196,174,224,78,137,190,250,1,215,79,59,165,134,166,104,90,60,178,239,177,139,209,98,15,189,92,134,200,252,87,204,178,122,239,24,135,132,211,172,167,149,149,11,213,82,209,64,114,136,167,174,252,38,73,41,43,227,246,32,1,133,167,103,32,126,83,51,195,193,220,248,90,246,159,161,107,17,224,103,242,142,7,97,9,130,230,13,97,139,0,177,72,255,23,6,62,158,65,9,101,38,191,4,16,231,132,45,38,110,217,167,208,132,235,179,212,233,210,98,77,71,35,6,5,111,44,193,92,132,162,57,27,81,74,140,15,60,204,224,229,127,71,22,98,47,92,197,29,201,79,59,90,196,142,34,102,221,4,219,42,133,102,181,74,67,0,168,84,48,47,102,44,90,10,121,234,216,170,204,8,153,53,195,249,252,220,121,176,129,56,119,34,133,176,199,7,114,180,102,20,79,59,246,76,138,3,114,135,70,38,46,190,77,39,234,62,218,109,10,233,42,244,233,153,161,94,17,103,186,59,49,250,99,18,36,206,212,228,245,255,6,89,166,168,164,249,219,79,68,208,202,24,42,118,109,48,81,114,90,250,206,38,25,28,205,75,140,8,251,39,87,212,25,186,212,144,48,89,45,177,169,174,17,175,65,44,7,17,247,48,228,219,17,161,253,218,244,185,255,236,7,229,42,40,229,141,225,254,101,208,73,158,170,234,56,203,246,202,32,52,21,125,110,207,120,21,16,216,143,117,118,108,191,197,123,111,154,217,247,195,238,133,128,211,180,142,230,123,221,251,239,27,147,36,13,81,213,8,114,3,149,111,247,208,178,130,79,24,10,95,37,155,95,236,150,212,101,87,166,252,108,185,102,226,251,115,188,34,144,98,129,234,144","name":"yillkid","address":"SUWVEALBVSOVMBSKPYJACHIDCXVAWSFWZJDOODOBVYJKBVTMOFQFNGVMTOWSBODZ9RLUQZB9PMPEGBKEZDYVQYHTPW","fingerprint":"AKKIBUZV99FYKVMLSSWUYRMFXTOMSJKXDPFWFMQHPLSA9UGAULAPKMBPUVMZPNCZATEEIEABZMETVZRDW","meta":{"revision":1,"created":1506670484879,"version":0,"updated":1506670484977},"$loki":1,"status":"error"}
/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:433 Uncaught TypeError: Cannot set property 'errorMessage' of undefined
    at addAccountResultsHandler (/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:433)
    at /home/yillkid/workspace/IOTA/iota1k/app/js/index.js:97
    at makeRequest.prepareResult (/home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:189)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:61)
    at exports.XMLHttpRequest.dispatchEvent (/home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591)
    at setState (/home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610)
    at IncomingMessage.<anonymous> (/home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447)
    at emitNone (events.js:91)
    at IncomingMessage.emit (events.js:188)
    at endReadableNT (_stream_readable.js:975)
addAccountResultsHandler @ /home/yillkid/workspace/IOTA/iota1k/app/js/index.js:433
(anonymous) @ /home/yillkid/workspace/IOTA/iota1k/app/js/index.js:97
makeRequest.prepareResult @ /home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:189
request.onreadystatechange @ /home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:61
dispatchEvent @ /home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591
setState @ /home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610
(anonymous) @ /home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447
emitNone @ events.js:91
emit @ events.js:188
endReadableNT @ _stream_readable.js:975
_combinedTickCallback @ internal/process/next_tick.js:80
_tickCallback @ internal/process/next_tick.js:104
/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:432 addAccountResultsHandler results.account: {"privateKey":"2,3,0,6,16,86,182,139,119,223,191,133,10,180,49,180,196,9,194,127,160,209,18,66,221,249,171,62,179,148,216,149,238,174,84,227,122,100,113,86,139,46,132,148,35,138,251,67,42,134,204,190,172,24,124,106,20,39,234,35,255,12,13,147,251,142,67,66,222,155,212,199,230,87,138,216,231,220,152,83,181,210,135,202,232,201,173,196,104,200,102,61,142,125,173,192,96,210,119,162,237,123,75,23,201,227,199,225,153,32,136,112,162,57,13,128,77,120,175,166,45,171,146,174,67,134,182,214,32,9,170,149,220,92,47,98,48,12,144,103,243,26,150,137,230,120,224,60,153,146,103,98,105,19,143,246,174,247,168,20,123,74,224,149,13,207,134,77,111,103,21,72,122,61,119,10,134,27,5,219,13,141,48,165,158,82,138,1,14,77,41,51,155,192,248,116,255,75,160,117,181,162,131,185,138,110,145,99,176,172,184,97,201,153,185,116,143,71,187,136,38,194,132,115,250,188,75,34,149,102,74,103,176,220,96,72,91,57,177,67,70,139,95,43,172,95,121,15,241,130,145,176,126,67,143,40,77,231,41,253,187,131,125,190,249,169,18,247,23,129,115,118,142,211,17,45,74,137,135,121,123,138,132,222,233,211,131,16,79,139,251,77,143,140,143,188,178,244,85,213,129,146,240,14,46,15,121,10,66,237,153,52,211,243,57,157,138,137,174,41,85,93,97,3,121,61,100,46,235,249,238,153,146,248,99,97,151,83,51,150,52,193,135,215,242,63,178,93,74,103,152,254,51,249,93,84,104,62,171,192,45,191,33,193,45,113,171,81,237,193,54,153,162,138,208,37,113,179,148,167,58,128,128,174,105,96,68,10,164,113,14,183,125,215,35,162,111,83,161,143,22,16,128,196,213,68,51,119,171,89,123,254,190,181,185,5,21,16,244,71,11,221,19,149,246,143,217,22,200,213,6,25,249,61,230,197,171,212,8,131,94,77,32,110,172,255,28,235,154,70,130,37,207,160,153,245,128,160,70,77,141,145,94,141,21,25,1,223,118,0,58,117,239,145,10,26,19,16,242,10,147,52,132,132,33,83,76,105,146,20,103,189,250,30,184,165,98,46,197,144,174,255,208,23,172,83,78,217,120,10,25,54,21,91,134,210,107,128,190,152,200,10,236,148,50,158,180,80,125,136,244,243,252,201,16,97,35,79,127,136,105,137,190,51,57,194,174,166,156,85,119,78,248,91,80,154,43,197,197,221,22,145,162,79,120,43,23,118,109,120,208,243,244,228,20,236,45,171,218,177,163,240,158,224,182,195,218,7,55,55,47,243,129,32,206,1,92,188,202,41,7,251,43,243,239,17,253,157,68,54,90,142,182,82,101,207,239,201,137,168,0,46,80,253,106,3,141,50,4,146,117,135,127,187,196,174,224,78,137,190,250,1,215,79,59,165,134,166,104,90,60,178,239,177,139,209,98,15,189,92,134,200,252,87,204,178,122,239,24,135,132,211,172,167,149,149,11,213,82,209,64,114,136,167,174,252,38,73,41,43,227,246,32,1,133,167,103,32,126,83,51,195,193,220,248,90,246,159,161,107,17,224,103,242,142,7,97,9,130,230,13,97,139,0,177,72,255,23,6,62,158,65,9,101,38,191,4,16,231,132,45,38,110,217,167,208,132,235,179,212,233,210,98,77,71,35,6,5,111,44,193,92,132,162,57,27,81,74,140,15,60,204,224,229,127,71,22,98,47,92,197,29,201,79,59,90,196,142,34,102,221,4,219,42,133,102,181,74,67,0,168,84,48,47,102,44,90,10,121,234,216,170,204,8,153,53,195,249,252,220,121,176,129,56,119,34,133,176,199,7,114,180,102,20,79,59,246,76,138,3,114,135,70,38,46,190,77,39,234,62,218,109,10,233,42,244,233,153,161,94,17,103,186,59,49,250,99,18,36,206,212,228,245,255,6,89,166,168,164,249,219,79,68,208,202,24,42,118,109,48,81,114,90,250,206,38,25,28,205,75,140,8,251,39,87,212,25,186,212,144,48,89,45,177,169,174,17,175,65,44,7,17,247,48,228,219,17,161,253,218,244,185,255,236,7,229,42,40,229,141,225,254,101,208,73,158,170,234,56,203,246,202,32,52,21,125,110,207,120,21,16,216,143,117,118,108,191,197,123,111,154,217,247,195,238,133,128,211,180,142,230,123,221,251,239,27,147,36,13,81,213,8,114,3,149,111,247,208,178,130,79,24,10,95,37,155,95,236,150,212,101,87,166,252,108,185,102,226,251,115,188,34,144,98,129,234,144,75,23,101,44,57,17,235,233,49,53,31,163,91,41,110,112,96,184,68,75,92,108,184,130,201,97,3,25,244,31,34,31,39,178,18,128,214,116,72,86,62,21,107,22,172,91,130,32,196,117,30,73,58,21,111,172,7,147,249,204,19,103,150,216,31,168,65,153,117,36,129,76,149,246,22,127,142,136,32,137,150,232,40,162,196,99,82,21,88,205,71,213,240","publicKey":"1,3,0,6,16,86,182,139,119,223,191,133,10,180,49,180,196,9,194,127,160,209,18,66,221,249,171,62,179,148,216,149,238,174,84,227,122,100,113,86,139,46,132,148,35,138,251,67,42,134,204,190,172,24,124,106,20,39,234,35,255,12,13,147,251,142,67,66,222,155,212,199,230,87,138,216,231,220,152,83,181,210,135,202,232,201,173,196,104,200,102,61,142,125,173,192,96,210,119,162,237,123,75,23,201,227,199,225,153,32,136,112,162,57,13,128,77,120,175,166,45,171,146,174,67,134,182,214,32,9,170,149,220,92,47,98,48,12,144,103,243,26,150,137,230,120,224,60,153,146,103,98,105,19,143,246,174,247,168,20,123,74,224,149,13,207,134,77,111,103,21,72,122,61,119,10,134,27,5,219,13,141,48,165,158,82,138,1,14,77,41,51,155,192,248,116,255,75,160,117,181,162,131,185,138,110,145,99,176,172,184,97,201,153,185,116,143,71,187,136,38,194,132,115,250,188,75,34,149,102,74,103,176,220,96,72,91,57,177,67,70,139,95,43,172,95,121,15,241,130,145,176,126,67,143,40,77,231,41,253,187,131,125,190,249,169,18,247,23,129,115,118,142,211,17,45,74,137,135,121,123,138,132,222,233,211,131,16,79,139,251,77,143,140,143,188,178,244,85,213,129,146,240,14,46,15,121,10,66,237,153,52,211,243,57,157,138,137,174,41,85,93,97,3,121,61,100,46,235,249,238,153,146,248,99,97,151,83,51,150,52,193,135,215,242,63,178,93,74,103,152,254,51,249,93,84,104,62,171,192,45,191,33,193,45,113,171,81,237,193,54,153,162,138,208,37,113,179,148,167,58,128,128,174,105,96,68,10,164,113,14,183,125,215,35,162,111,83,161,143,22,16,128,196,213,68,51,119,171,89,123,254,190,181,185,5,21,16,244,71,11,221,19,149,246,143,217,22,200,213,6,25,249,61,230,197,171,212,8,131,94,77,32,110,172,255,28,235,154,70,130,37,207,160,153,245,128,160,70,77,141,145,94,141,21,25,1,223,118,0,58,117,239,145,10,26,19,16,242,10,147,52,132,132,33,83,76,105,146,20,103,189,250,30,184,165,98,46,197,144,174,255,208,23,172,83,78,217,120,10,25,54,21,91,134,210,107,128,190,152,200,10,236,148,50,158,180,80,125,136,244,243,252,201,16,97,35,79,127,136,105,137,190,51,57,194,174,166,156,85,119,78,248,91,80,154,43,197,197,221,22,145,162,79,120,43,23,118,109,120,208,243,244,228,20,236,45,171,218,177,163,240,158,224,182,195,218,7,55,55,47,243,129,32,206,1,92,188,202,41,7,251,43,243,239,17,253,157,68,54,90,142,182,82,101,207,239,201,137,168,0,46,80,253,106,3,141,50,4,146,117,135,127,187,196,174,224,78,137,190,250,1,215,79,59,165,134,166,104,90,60,178,239,177,139,209,98,15,189,92,134,200,252,87,204,178,122,239,24,135,132,211,172,167,149,149,11,213,82,209,64,114,136,167,174,252,38,73,41,43,227,246,32,1,133,167,103,32,126,83,51,195,193,220,248,90,246,159,161,107,17,224,103,242,142,7,97,9,130,230,13,97,139,0,177,72,255,23,6,62,158,65,9,101,38,191,4,16,231,132,45,38,110,217,167,208,132,235,179,212,233,210,98,77,71,35,6,5,111,44,193,92,132,162,57,27,81,74,140,15,60,204,224,229,127,71,22,98,47,92,197,29,201,79,59,90,196,142,34,102,221,4,219,42,133,102,181,74,67,0,168,84,48,47,102,44,90,10,121,234,216,170,204,8,153,53,195,249,252,220,121,176,129,56,119,34,133,176,199,7,114,180,102,20,79,59,246,76,138,3,114,135,70,38,46,190,77,39,234,62,218,109,10,233,42,244,233,153,161,94,17,103,186,59,49,250,99,18,36,206,212,228,245,255,6,89,166,168,164,249,219,79,68,208,202,24,42,118,109,48,81,114,90,250,206,38,25,28,205,75,140,8,251,39,87,212,25,186,212,144,48,89,45,177,169,174,17,175,65,44,7,17,247,48,228,219,17,161,253,218,244,185,255,236,7,229,42,40,229,141,225,254,101,208,73,158,170,234,56,203,246,202,32,52,21,125,110,207,120,21,16,216,143,117,118,108,191,197,123,111,154,217,247,195,238,133,128,211,180,142,230,123,221,251,239,27,147,36,13,81,213,8,114,3,149,111,247,208,178,130,79,24,10,95,37,155,95,236,150,212,101,87,166,252,108,185,102,226,251,115,188,34,144,98,129,234,144","name":"yillkid","address":"SUWVEALBVSOVMBSKPYJACHIDCXVAWSFWZJDOODOBVYJKBVTMOFQFNGVMTOWSBODZ9RLUQZB9PMPEGBKEZDYVQYHTPW","fingerprint":"AKKIBUZV99FYKVMLSSWUYRMFXTOMSJKXDPFWFMQHPLSA9UGAULAPKMBPUVMZPNCZATEEIEABZMETVZRDW","meta":{"revision":1,"created":1506670484879,"version":0,"updated":1506670484977},"$loki":1,"status":"error"}
/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:433 Uncaught TypeError: Cannot set property 'errorMessage' of undefined
    at addAccountResultsHandler (/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:433)
    at /home/yillkid/workspace/IOTA/iota1k/app/js/index.js:94
    at makeRequest.prepareResult (/home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:189)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:61)
    at exports.XMLHttpRequest.dispatchEvent (/home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591)
    at setState (/home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610)
    at IncomingMessage.<anonymous> (/home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447)
    at emitNone (events.js:91)
    at IncomingMessage.emit (events.js:188)
    at endReadableNT (_stream_readable.js:975)
addAccountResultsHandler @ /home/yillkid/workspace/IOTA/iota1k/app/js/index.js:433
(anonymous) @ /home/yillkid/workspace/IOTA/iota1k/app/js/index.js:94
makeRequest.prepareResult @ /home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:189
request.onreadystatechange @ /home/yillkid/workspace/IOTA/iota1k/node_modules/iota.lib.js/lib/utils/makeRequest.js:61
dispatchEvent @ /home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591
setState @ /home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610
(anonymous) @ /home/yillkid/workspace/IOTA/iota1k/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447
emitNone @ events.js:91
emit @ events.js:188
endReadableNT @ _stream_readable.js:975
_combinedTickCallback @ internal/process/next_tick.js:80
_tickCallback @ internal/process/next_tick.js:104
23/home/yillkid/workspace/IOTA/iota1k/app/js/index.js:462 in handler error:  no results in findTransactions callback for tag IOTALKMESSAGE99999999999999`

**Comment by xx10t4** [comment]
This is likely a result of the recent change to IOTA Tangle transaction structure. Please try upgrading to iota1k 0.0.7. https://github.com/xx10t4/iota1k/releases/tag/0.0.7

Also, very important WRT the info you included in this issue. The info is of course very helpful but please note that you included the details of your private key, which is now public information. After you upgrade  and go through the "Retry" process as described in the release notes, I recommend that you delete that account and create a new one. That will automatically generate a new private key for you. And to be clear, the seed you use to login to iota1k is NOT exposed so you don't need to change that. Just the account *yillkid@AKKIBUZV99FYKVMLSSWU...* should be deleted.

**Comment by yillkid** [comment]
Thank you very much, the key just generate by a random seed that I generate for testing.
