### ISSUE TITLE
Mask Seed on Log-in and Display 3 Characters Associated with Seed

### ISSUE THREAD

**Issue by ghost** [xx10t4/iota1k#3]
In order to provide a similar experience to using the IOTA light wallet I think it would be best that when logging in the seed is masked and the 3 character string associated with the seed is displayed next to it.  This will increase security by not revealing the seed as well as offering the ability to display the string associated to the account to ensure the user is entering the correct messaging account.

**Comment by xx10t4** [comment]
Good ideas, done in release 0.0.6.
