### ISSUE TITLE
can not add contact

### ISSUE THREAD

**Issue by vascoosx** [xx10t4/iota1k#4]
I am using ubuntu but I could not add a contact. Even though I am adding a contact through the interface it does not appear in the app.

**Comment by joepio** [comment]
Just to make sure:
Have you set up a valid node? Press the gear icon and add one (e.g. `http://iota.bitfinex.com:80`). 
Have you set up an account? Press the + icon next to accounts.

**Comment by xx10t4** [comment]
Is it definitely a valid contact? The app needs to be able to find the contact's public key on the Tangle. Another possibility is if the contact created their account on a different node than the node you are using, those nodes need to be synced, which can take a little time if one or the other is not well connected.

**Comment by vascoosx** [comment]
OK, I was trying to add a fresh address not seen in the Tangle. I created a contact and I was able to send thanks @xx10t4

**Comment by xx10t4** [comment]
Thanks for checking out the app!
