### ISSUE TITLE
not able to remove invalid accounts

### ISSUE THREAD

**Issue by seriouslylost** [xx10t4/iota1k#7]
1) tried to make an account
2) node down - account not made
3) now it lists my stillborn account as "account not found" and there is no button to click to remove it, just retry

**Comment by xx10t4** [comment]
The retry should create the account, assuming the node has become available. Did that not work for you?

**Comment by seriouslylost** [comment]
yes. retried. success. deleted account. all ok.



________________________________

**Comment by xx10t4** [comment]
Thanks for checking.
